In [2]:
# loading necessSary libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# loading the dataset

advertisers= pd.read_csv('advertisers_info.csv') 
user_ad = pd.read_csv('user_ad_views.csv')
print(advertisers.head())
print("-------------------------------------------------------")
print(user_ad.head())

  country            advertiser       cpi
0      US  g6HqZe7Ev4uAnvzcIWYC  0.500000
1      US  0pWbqOUFkryuIs6BtsS6  0.551724
2      US  ek5DxAfTfZBW2TihkbRR  0.603448
3      US  fwXiEmV4DPhgtCE7kdhB  0.655172
4      US  gqFdk16BCaEiyOJZEPWl  0.706897
-------------------------------------------------------
   install           user id              game app country  \
0        0  4Hw9w1ahkO6YyXjg  4orCk3bBPLAf3qnZrE2m      US
1        0  hjzrSmIgdjaEUzOV  4orCk3bBPLAf3qnZrE2m      DE
2        0  4Hw9w1ahkO6YyXjg  4orCk3bBPLAf3qnZrE2m      US
3        0  NQiVDdo7l44MvMMo  IUgSZ6L7m92e14QKrGFd      BR
4        0  n074Wye5PjzGtz3U  4orCk3bBPLAf3qnZrE2m      IN

             advertiser  age  user quality score   createdat  spending  \
0  IsnShevMFAoSETkREGbb  4.0                   1  1675209600  0.020103
1  3SABwx0gaB06Nf7vtLbM  2.0                   1  1675209600  0.012934
2  IsnShevMFAoSETkREGbb  4.0                   1  1675209600  0.020103
3  0T7RXIs4iDYN2cUJ1Cra  2.0                   2  1675209613  0.000637
4  fwXiEmV4DPhgtCE7kdhB  3.0                   1  1675209621  0.000288

   earning carrier  mccmnc
0      0.0   lqkHf  312503
1      0.0   Mg4KZ  262777
2      0.0   lqkHf  312503
3      0.0   Llb0G  724670
4      0.0   czVgl  404777

In [4]:
# print columns and unique values for both datasets

print(advertisers.columns)
print(advertisers.nunique())

print(user_ad.columns)
print(user_ad.nunique())

Index(['country', 'advertiser', 'cpi'], dtype='object')
country         7
advertiser     30
cpi           204
dtype: int64
Index(['install', 'user id', 'game app', 'country', 'advertiser', 'age',
       'user quality score', 'createdat', 'spending', 'earning', 'carrier',
       'mccmnc'],
      dtype='object')
install                    2
user id               300024
game app                   7
country                    7
advertiser                30
age                        5
user quality score         3
createdat             281841
spending                 204
earning                  208
carrier                   20
mccmnc                   413
dtype: int64

In [5]:
# print shape
print(advertisers.shape)
print(user_ad.shape)

(210, 3)
(310024, 12)

In [6]:
# Check null values in both datasets

print(advertisers.isnull().sum())
print(user_ad.isnull().sum())

country       0
advertiser    0
cpi           0
dtype: int64
install                   0
user id                   0
game app                  0
country                   0
advertiser                0
age                   13854
user quality score        0
createdat                 0
spending               1045
earning                   0
carrier               40509
mccmnc                    0
dtype: int64

In [7]:
# datatypes of user_ad dataset
print(user_ad.dtypes)

install                 int64
user id                object
game app               object
country                object
advertiser             object
age                   float64
user quality score      int64
createdat               int64
spending              float64
earning               float64
carrier                object
mccmnc                  int64
dtype: object

In [8]:
# check unique advitersiers in both datasets

print(advertisers['advertiser'].nunique())
print(user_ad['advertiser'].nunique())

30
30

In [9]:
# # add cpi column to user_ad dataset
# user_ad = user_ad.merge(advertisers[['advertiser','cpi']], on='advertiser', how='left')
# print(user_ad.head())

In [10]:
# Grouping the dataset based on advertiser to check the impact of the advertiser on the dataset
# Also aggregating the sum of total spending, earning, and installs

grouped_advertiser = user_ad.groupby('advertiser').agg(
    counts=('advertiser', 'size'),
    total_spending=('spending', 'sum'),
    total_earning=('earning', 'sum'),
).reset_index()

# Adding a profit column
grouped_advertiser['profit'] = grouped_advertiser['total_earning'] - grouped_advertiser['total_spending']

print(grouped_advertiser)

              advertiser  counts  total_spending  total_earning     profit
0   0T7RXIs4iDYN2cUJ1Cra   10390      106.356648     104.768276  -1.588372
1   0pWbqOUFkryuIs6BtsS6   10435       59.977280      53.732414  -6.244866
2   3SABwx0gaB06Nf7vtLbM   10288      114.060502     113.866207  -0.194295
3   9OMDwsBWiyVTC2sV23QG   10259      214.788200     231.640000  16.851800
4   DggekooIvQUnkJqeBInB   10320       82.405006      75.429655  -6.975350
5   IsnShevMFAoSETkREGbb   10236       98.582284     106.027414   7.445129
6   Iw2oPsQRPcV2Wh0Yust8   10268      132.120154     121.716034 -10.404120
7   P9t0U8mi6YhaiBdI6CcS   10231      165.178906     164.696034  -0.482871
8   Rd6lCNb8JSuLncR1zdTo   10540      185.506329     204.346897  18.840568
9   TtNDtGgXHwYKi1SnCFgW   10265       93.986086     100.767241   6.781155
10  UDSRYiwIvhvuhd2hlWW5   10306      156.133074     155.210000  -0.923074
11  WtEYQX4kuXyvO02qokWb   10414      178.468343     172.457759  -6.010584
12  aU3KhkHD09j5xbdJ7gj9   10221      197.013160     195.256552  -1.756608
13  bF9oV9i8XlNq3Sh2PJiX   10281      194.637399     231.346207  36.708808
14  ek5DxAfTfZBW2TihkbRR   10332       64.932374      62.957759  -1.974616
15  fsf1VXh3qzzd9awavuL9   10305      143.921072     139.582414  -4.338658
16  fwXiEmV4DPhgtCE7kdhB   10574       71.690892      67.666207  -4.024685
17  g6HqZe7Ev4uAnvzcIWYC   10317       54.552520      51.800000  -2.752520
18  gqFdk16BCaEiyOJZEPWl   10475       77.536387      72.258966  -5.277421
19  hnVGfx0P4xyVU2Bk6UVt   10289      210.044712     200.652931  -9.391781
20  i4XAVmM2O71iQ3zbCYfI   10212      169.355059     199.814483  30.459423
21  jth3Fg7Px8uh4N1tEupI   10417      209.047110     202.627586  -6.419524
22  kx79GxvyIDzXAudvrCkY   10367      160.217170     159.811724  -0.405446
23  nF6yO8APP4usjB3JE8On   10510      123.706341     112.550862 -11.155479
24  nXN3O5QHsWaGM4NrZZdj   10299       87.057808      90.167069   3.109261
25  ndREtPhnDnoOsdsWYyvu   10200      139.562265     145.116552   5.554287
26  pe4bZTNbmutI7k5z3L8T   10167      186.149199     188.486897   2.337697
27  swuCaeAq7Ynz62Qxgjle   10342      127.882981     131.251724   3.368743
28  uj6SjhziNLHHbnNOLMys   10470      150.811972     148.703448  -2.108524
29  vHGDffsoIP65HOLtNamQ   10294      110.242497     108.783793  -1.458704

In [11]:
# list top advertisers form grouped dataset based on profit made
top_advertisers = grouped_advertiser.sort_values('profit', ascending=False).head(5)
top_advertisers

              advertiser  counts  total_spending  total_earning     profit
13  bF9oV9i8XlNq3Sh2PJiX   10281      194.637399     231.346207  36.708808
20  i4XAVmM2O71iQ3zbCYfI   10212      169.355059     199.814483  30.459423
8   Rd6lCNb8JSuLncR1zdTo   10540      185.506329     204.346897  18.840568
3   9OMDwsBWiyVTC2sV23QG   10259      214.788200     231.640000  16.851800
5   IsnShevMFAoSETkREGbb   10236       98.582284     106.027414   7.445129

In [12]:
user_ad.head()

,install,user id,game app,country,advertiser,age,user quality score,createdat,spending,earning,carrier,mccmnc
0,0,4Hw9w1ahkO6YyXjg,4orCk3bBPLAf3qnZrE2m,US,IsnShevMFAoSETkREGbb,4.0,1,1675209600,0.020103,0.0,lqkHf,312503
1,0,hjzrSmIgdjaEUzOV,4orCk3bBPLAf3qnZrE2m,DE,3SABwx0gaB06Nf7vtLbM,2.0,1,1675209600,0.012934,0.0,Mg4KZ,262777
2,0,4Hw9w1ahkO6YyXjg,4orCk3bBPLAf3qnZrE2m,US,IsnShevMFAoSETkREGbb,4.0,1,1675209600,0.020103,0.0,lqkHf,312503
3,0,NQiVDdo7l44MvMMo,IUgSZ6L7m92e14QKrGFd,BR,0T7RXIs4iDYN2cUJ1Cra,2.0,2,1675209613,0.000637,0.0,Llb0G,724670
4,0,n074Wye5PjzGtz3U,4orCk3bBPLAf3qnZrE2m,IN,fwXiEmV4DPhgtCE7kdhB,3.0,1,1675209621,0.000288,0.0,czVgl,404777

In [13]:
# add cpi column to user_ad dataset on country and gameapp
user_ad = pd.merge(user_ad, advertisers, on=['advertiser','country'], how='inner')
user_ad.head()

,install,user id,game app,country,advertiser,age,user quality score,createdat,spending,earning,carrier,mccmnc,cpi
0,0,4Hw9w1ahkO6YyXjg,4orCk3bBPLAf3qnZrE2m,US,IsnShevMFAoSETkREGbb,4.0,1,1675209600,0.020103,0.0,lqkHf,312503,0.913793
1,0,4Hw9w1ahkO6YyXjg,4orCk3bBPLAf3qnZrE2m,US,IsnShevMFAoSETkREGbb,4.0,1,1675209600,0.020103,0.0,lqkHf,312503,0.913793
2,0,KelbPqjrVTMRADOO,gVRWs2fMrsM0PEhG18hX,US,IsnShevMFAoSETkREGbb,3.0,1,1675211245,0.020103,0.0,NaN,312670,0.913793
3,0,4D9iIBW8mM0b5h0o,gVRWs2fMrsM0PEhG18hX,US,IsnShevMFAoSETkREGbb,4.0,1,1675216040,0.020103,0.0,lFAHF,312643,0.913793
4,0,ed06S6KVQLND3qfU,4orCk3bBPLAf3qnZrE2m,US,IsnShevMFAoSETkREGbb,2.0,2,1675216920,0.020103,0.0,NaN,312296,0.913793

In [14]:
# check average and median cpi per country and gameapp
cpi_country = user_ad.groupby(['country', 'game app']).agg(
    avg_cpi=('cpi', 'mean'),
    median_cpi=('cpi', 'median')
).reset_index()

cpi_country

   country              game app   avg_cpi  median_cpi
0       AT  1yXfAufLTi688uUPvfZm  0.877298    0.893103
1       AT  4orCk3bBPLAf3qnZrE2m  0.872905    0.893103
2       AT  8r92kfSTOHs7KSd0zCU8  0.869305    0.856897
3       AT  IUgSZ6L7m92e14QKrGFd  0.879395    0.893103
4       AT  eVy14GUauNxRgry1jzzc  0.875058    0.856897
5       AT  gVRWs2fMrsM0PEhG18hX  0.873600    0.856897
6       AU  1yXfAufLTi688uUPvfZm  0.745588    0.734483
7       AU  4orCk3bBPLAf3qnZrE2m  0.750488    0.765517
8       AU  8r92kfSTOHs7KSd0zCU8  0.749747    0.765517
9       AU  IUgSZ6L7m92e14QKrGFd  0.750594    0.765517
10      AU  eVy14GUauNxRgry1jzzc  0.749733    0.734483
11      AU  gVRWs2fMrsM0PEhG18hX  0.744524    0.734483
12      BR  1yXfAufLTi688uUPvfZm  0.037315    0.036724
13      BR  4orCk3bBPLAf3qnZrE2m  0.037709    0.038276
14      BR  8r92kfSTOHs7KSd0zCU8  0.037822    0.038276
15      BR  IUgSZ6L7m92e14QKrGFd  0.037318    0.036724
16      BR  eVy14GUauNxRgry1jzzc  0.037573    0.036724
17      BR  gVRWs2fMrsM0PEhG18hX  0.037408    0.036724
18      DE  1yXfAufLTi688uUPvfZm  0.686973    0.701724
19      DE  4orCk3bBPLAf3qnZrE2m  0.687242    0.673276
20      DE  8r92kfSTOHs7KSd0zCU8  0.689111    0.701724
21      DE  IUgSZ6L7m92e14QKrGFd  0.689932    0.673276
22      DE  eVy14GUauNxRgry1jzzc  0.680664    0.673276
23      DE  gVRWs2fMrsM0PEhG18hX  0.686941    0.673276
24      GB  1yXfAufLTi688uUPvfZm  0.563987    0.574138
25      GB  4orCk3bBPLAf3qnZrE2m  0.561207    0.574138
26      GB  8r92kfSTOHs7KSd0zCU8  0.561557    0.574138
27      GB  IUgSZ6L7m92e14QKrGFd  0.560109    0.550862
28      GB  eVy14GUauNxRgry1jzzc  0.562629    0.550862
29      GB  gVRWs2fMrsM0PEhG18hX  0.562977    0.574138
30      IN  1yXfAufLTi688uUPvfZm  0.024761    0.024483
31      IN  4orCk3bBPLAf3qnZrE2m  0.024845    0.024483
32      IN  8r92kfSTOHs7KSd0zCU8  0.025081    0.025517
33      IN  IUgSZ6L7m92e14QKrGFd  0.024974    0.024483
34      IN  eVy14GUauNxRgry1jzzc  0.024959    0.024483
35      IN  gVRWs2fMrsM0PEhG18hX  0.024941    0.024483
36      US  1yXfAufLTi688uUPvfZm  2.801751    1.224138
37      US  4orCk3bBPLAf3qnZrE2m  2.703184    1.275862
38      US  8r92kfSTOHs7KSd0zCU8  2.600529    1.224138
39      US  IUgSZ6L7m92e14QKrGFd  2.733267    1.224138
40      US  eVy14GUauNxRgry1jzQD  1.275862    1.275862
41      US  eVy14GUauNxRgry1jzzc  2.634708    1.275862
42      US  gVRWs2fMrsM0PEhG18hX  2.591947    1.275862